
import React, { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription, CardFooter } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { useToast } from '@/hooks/use-toast';
import { 
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue
} from '@/components/ui/select';

const topicOptions = [
  "Mathematics",
  "Physics",
  "Chemistry",
  "Biology",
  "Computer Science",
  "History",
  "Geography",
  "Literature",
  "Language Arts",
  "Economics"
];

const SamplesRequest = () => {
  const { toast } = useToast();
  const [selectedTopic, setSelectedTopic] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [samples, setSamples] = useState<string[]>([]);

  const handleRequestSamples = () => {
    if (!selectedTopic) {
      toast({
        title: "Topic Required",
        description: "Please select a topic to request samples",
        variant: "destructive"
      });
      return;
    }

    setIsLoading(true);
    
    // Simulate API call
    setTimeout(() => {
      // Mock sample questions
      const mockSamples = [
        `What is the primary function of ${selectedTopic} in modern applications?`,
        `Explain the core principles of ${selectedTopic} with examples.`,
        `Compare and contrast traditional vs. contemporary approaches to ${selectedTopic}.`,
        `What role does ${selectedTopic} play in solving real-world problems?`,
      ];
      
      setSamples(mockSamples);
      setIsLoading(false);
      
      toast({
        title: "Samples Retrieved",
        description: `Successfully loaded 4 sample questions for ${selectedTopic}`,
      });
    }, 1500);
  };

  return (
    <Card className="w-full animate-scale-in card-hover">
      <CardHeader>
        <CardTitle>Request Samples</CardTitle>
        <CardDescription>
          Select a topic to view sample questions generated by our system
        </CardDescription>
      </CardHeader>
      <CardContent>
        <div className="space-y-6">
          <div className="space-y-2">
            <Label htmlFor="topic">Topic</Label>
            <Select value={selectedTopic} onValueChange={setSelectedTopic}>
              <SelectTrigger>
                <SelectValue placeholder="Select a topic" />
              </SelectTrigger>
              <SelectContent>
                {topicOptions.map((topic) => (
                  <SelectItem key={topic} value={topic}>{topic}</SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>

          <Button 
            onClick={handleRequestSamples} 
            disabled={isLoading} 
            className="w-full button-glow"
          >
            {isLoading ? "Loading..." : "Request Samples"}
          </Button>

          {samples.length > 0 && (
            <div className="mt-6 space-y-4 animate-fade-in">
              <h3 className="text-lg font-medium">Sample Questions</h3>
              <ul className="space-y-3">
                {samples.map((sample, index) => (
                  <li key={index} className="p-3 rounded-md bg-secondary/50 border border-border/50">
                    {sample}
                  </li>
                ))}
              </ul>
            </div>
          )}
        </div>
      </CardContent>
      <CardFooter className="flex justify-between border-t pt-6">
        <p className="text-sm text-muted-foreground">
          View samples before generating full question sets
        </p>
      </CardFooter>
    </Card>
  );
};

export default SamplesRequest;
